version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.2

parameters:
  action:
    type: 'string'
    default: ''
  env:
    type: 'string'
    default: 'dev'

jobs:
  deploy-to-azure:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - azure-cli/login-with-user:
          alternate-tenant: true
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_TENANT` env var
workflows:
  example-workflow:
    jobs:
      - login-to-azure

