version: 2.1
orbs:
  node: circleci/node@4.7
  azure-cli: circleci/azure-cli@1.2.2
parameters:
  env:
    type: string
    default: "dev"

commands:
  make-file:
    steps:
      - run:
          working_directory: /tmp
          command: touch test
      - run:
          command: ls
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: tmp
          paths:
            - .
  copy-to-azure:
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp
      - run:
          command: ls
      - run:
          command:  az storage blob upload --overwrite true --name ./tmp/test  --container-name update-template-<< pipeline.parameters.env >> --account-name updatetemplatestorage --file test --account-key $ACCOUNT_KEY_<< pipeline.parameters.env >>--connection-string $CONNECTION_STRING_<< pipeline.parameters.env >>
jobs:
  build-app:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - make-file
  copy-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - copy-to-azure
workflows:
  example-workflow:
    jobs:
      - build-app
      - copy-to-azure:
          requires:
            - build-app