version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.2
parameters:
  env:
    type: string
    default: "dev"

commands:
  copy-to-azure:
    steps:
      - run:
          command: touch test
      - run:
          command:  az storage blob upload --name test  --container-name update-template-<< pipeline.parameters.env >> --account-name updatetemplatestorage --file test --account-key $ACCOUNT_KEY_<< pipeline.parameters.env >>--connection-string $CONNECTION_STRING_<< pipeline.parameters.env >>
jobs:
  copy:
    executor: azure-cli/azure-docker
    steps:
      - run:
          command: touch test
      - copy-to-azure
workflows:

  example-workflow:
    jobs:
      - copy


